development:
 adapter: mysql2
 encoding: utf8
 database: smart_buildings_manager_development
 pool: 5
 username: root
 password:

test:
 adapter: mysql2
 encoding: utf8
 database: smart_buildings_manager_test
 pool: 5
 username: root
 password:

production:
 adapter: mysql2
 encoding: utf8
 database: smart_buildings_manager_production
 pool: 5
 username: root
 password:
